/* Generates assets/js/search-index.js from page data */
const fs = require("fs");
const path = require("path");
const services = require("./data-services");
const industries = require("./data-industries");

const idx = [];

services.forEach((d) => idx.push({
  t: d.name, u: (require("./paths").MAP[d.key || d.file.replace(".html", "")] || {}).dir ? require("./paths").MAP[d.key || d.file.replace(".html", "")].dir + "/index.html" : d.file,
  k: (d.heroTitle + " " + d.heroLead + " " + d.points.join(" ") + " AWS Azure GCP " + d.name).toLowerCase(),
  c: "Service", d: d.heroLead.slice(0, 120) + "...",
}));
industries.forEach((d) => idx.push({
  t: d.name, u: "industries/" + d.file.replace("industry-", "").replace(".html", "") + "/index.html",
  k: (d.heroTitle + " " + d.heroLead + " " + d.chips.join(" ") + " " + d.name).toLowerCase(),
  c: "Industry", d: d.heroLead.slice(0, 120) + "...",
}));

const statics = [
  ["Home", "index.html", "home data ai software company dubai custom software cloud", "Software Disruption — Data, AI & Software Company in Dubai"],
  ["All Services", "services/index.html", "services overview technology solutions", "High-impact technology solutions for modern businesses"],
  ["Industries We Serve", "industries/index.html", "industries sectors domains region gcc uae ksa", "Technology engineered for your industry and region"],
  ["About Us", "about/index.html", "about company fzco dubai mission vision values team", "Dubai-based global technology company"],
  ["Why Choose Us", "why-us/index.html", "why us quality communication ip ownership track record", "A technology partner committed to excellence"],
  ["Client Testimonials", "testimonials/index.html", "reviews clients feedback references", "What our clients say"],
  ["Contact Us", "contact/index.html", "contact consultation phone email location dubai quote", "Let's build your next software solution"],
  ["Blog", "blog/index.html", "blog insights articles resources", "Insights & resources"],
  ["ZATCA E-Invoicing Penalties Saudi Arabia", "blog/e-invoicing-penalties-saudi-arabia/index.html", "zatca e-invoicing fatoora ksa tax article 45 fines compliance", "What ZATCA non-compliance actually costs you"],
  ["IT Staff Augmentation Saudi Arabia Cost", "blog/it-staff-augmentation-saudi-arabia/index.html", "staff augmentation hiring gosi iqama levy cost ksa", "Real cost of hiring in-house vs augmented team"],
  ["Rust vs C++", "blog/rust-vs-cpp/index.html", "rust cpp memory safety performance cisa programming languages", "Performance, memory management and safety"],
  ["Case Studies", "case-studies/index.html", "case studies portfolio work projects", "Selected work & case studies"],
  ["How We Work", "how-we-work/index.html", "process delivery agile model methodology", "Our delivery model — from idea to impact"],
  ["Our Team", "team/index.html", "team leadership waqas yousuf shahzad people", "Meet our leadership team"],
  ["Careers", "careers/index.html", "careers jobs hiring engineer positions", "Build your career where ideas ship"],
  ["FAQs", "faq/index.html", "faq questions answers engagement ip nda", "Frequently asked questions"],
  ["Privacy Policy", "privacy/index.html", "privacy policy data protection", "Privacy policy"],
  ["Terms of Service", "terms/index.html", "terms of service legal", "Terms of service"],
];
statics.forEach(([t, u, k, d]) => idx.push({ t, u, k, c: "Page", d }));

const out = "/* Search index — generated by tools/gen-search.js */\nwindow.SEARCH_INDEX = " + JSON.stringify(idx, null, 1) + ";";
fs.writeFileSync(path.join(__dirname, "..", "assets", "js", "search-index.js"), out);
console.log("search-index.js:", idx.length, "entries");
